language: node_js
node_js:
- iojs
- '7'
deploy:
  provider: heroku
  api_key:
    secure: JHHV1KGbB8yHIPhcz722rPeya/2P9QtuHF/mQ0p/qKQ/1IvsbhIEhk7f/00gMcyANL2QYxxxGe5LzBBajSXM7hG+1Z/Y8M/ifYVy8UqRcY1aXAcSsmadguDjnzEsVLLmJ99s6DjheaMXZpm+LWRTIpaTDpHQI3ExuWnBzNES8P46W7Kw4nD84XCh3Kj+T8piswtD1Tk7vzZKgqSOq0vH5FHvBJJTTqIJJT4p2QgMuEHgLOObhD0AQU34wFR8evtPA/RskAB3K2ct4TaXd+qc63peuETBVdhrBEFIXW6VDHplDZHRNf3IIi6IPeE4gA/JmBY31JrCK9GdWrlewvPBZQ6Gk0BAHm1DnIvXOgq3J+1cJaK0Ya0i4JVOVe4Wpok8QqKn0Bu4DpkfvSn3pVUKAWpgNe0/IEy/A/vldgOa9yVFeY1HvzFe9rH21VNusrZjvEVoWrAns1dHgocaQppavgNSIPJX+tNCWL7cTtpDc7Wz6nzWUAsJfb5CMEcSkM2z3IHu0f29lvGfJy0OPmV5Z07eHvvJVovCis8lRQL+KfbL4VMD37CC9MBTHYmkGwJEV29jh0kIUqDQTB3v+Wgq/3lDjMeXuPtDGVFKVESWoHFVLvjsJUXXU6LnuHRUyNU32IPsZWFfq1JBcYklYcdrdu4CsAo9SSAlxHzUzfVDtbY=
  app: patlinkcut
